[package]
name = "parsefile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = {version = "0.7.1", features = ["alloc"]}
unindent = "0.2.3"
comfy-table = "7.0.1"